// Execution core: domain exports + scratchpad utilities
//
// The execution module owns the run lifecycle, recipe registry, decision tracing,
// and approval workflows. Domain services from `index.domain.ts` reach callers
// through this facade, along with the scratchpad runtime helpers.

// Domain exports: run lifecycle, workers, recipe registry, types, agent-runtime primitives
export {
  registerRecipe,
  startRun,
  startRunInTx,
  getRun,
  signalRun,
  signalRunInTx,
  replayRun,
  cancelRun,
  startAgentWorker,
  stopAgentWorker,
  startSubAgentJoinWakeWorker,
  stopSubAgentJoinWakeWorker,
  verifyMeteringModels,
  isInternalWorkflowSlug,
  listPublicWorkflows,
  listResumeOnlyWorkflows,
  normalizeDecisionTraceKey,
  persistChatTurnRunInTx,
  redeliverRun,
  closeAgentQueue,
  closeSubAgentJoinWakeQueue,
  CHARS_PER_TOKEN,
  compactTranscript,
  compactWithRetry,
  estimateSerializedTokens,
  estimateTranscriptTokens,
  buildConnectedSummaryFromAvailability,
  formatRuntimeTimeGrounding,
  resolveRuntimeGroundingAnchor,
  foldToolSurfaceState,
  systemToolKernel,
  toolRuntimeForRun,
  toolSurfaceStateFields,
  appendModelResponseMessages,
  aggregateRunUsage,
  shouldPublishToolStarted,
  toolCardStarted,
  toolCardTerminal,
  toolEventOutcome,
  pendingToolCallSchema,
  CHAT_TURN_CAP_MAX,
  openChatTurnRetries,
  resetChatTurnRetryBudgets,
  PREVIEW_CHARS,
  registerWorkflowReadinessCheck,
  joinChildRun,
  scheduleSubAgentJoinWakeJob,
  expireStaging,
  startApprovalExpiryWorker,
  stopApprovalExpiryWorker,
  startApprovalNotificationWorker,
  stopApprovalNotificationWorker,
  isTerminalChildStatus,
  listSpawnedChildRuns,
  readChildRunOutcome,
} from "./index.domain";
export type {
  RunStatus,
  Step,
  StepContext,
  StepResult,
  WakeCondition,
  Workflow,
  WorkflowInput,
  CancelOutcome,
  SignalArgs,
  SignalOutcome,
  WorkflowReadinessVerdict,
  JoinChildRunDeps,
  ParkSignal,
  ExpireStagingResult,
  StartApprovalExpiryWorkerOpts,
  StartApprovalNotificationWorkerOpts,
  ChildRunOutcome,
  AgentDbExecutor,
} from "./index.domain";

// Scratchpad exports: per-run scratch helpers and health spans
export {
  RUNTIME_SCRATCH_READ,
  RUNTIME_SCRATCH_WRITE,
  RUNTIME_SCRATCH_PROMOTE,
  RUNTIME_SCRATCH_SNAPSHOT,
  _setScratchRuntimeSpanStarterForTests,
  writeScratch,
  readScratch,
  promoteScratch,
  snapshotScratchToPostgres,
} from "./scratchpad/index";
export type { WriteScratchArgs, ReadScratchArgs, PromoteScratchArgs } from "./scratchpad/index";
