// Transitional barrel: re-exports automation domain logic from @alfred/assistant/automation
// and routes from ./routes for backward compatibility during the 6B migration.
// This keeps @alfred/api/backend surface byte-identical while moving the domain module.
export {
  DEFAULT_WORKFLOW_TIMEZONE,
  computeNextRunAt,
  resolveWorkflowTimezone,
  validateCronTrigger,
  canonicalWorkflowDefinition,
  workflowRevisionContentHash,
  activateWorkflow,
  clearWorkflowBlocked,
  createWorkflowDraft,
  recoverWorkflowDraft,
  reviseWorkflow,
  reviseWorkflowFromPatch,
  setWorkflowBlocked,
  setWorkflowStatus,
  validateWorkflowDefinition,
  prepareWorkflowApprovalEdit,
  restageWorkflowApproval,
  acceptEvent,
  seedBuiltinWorkflowsForAllUsers,
  seedBuiltinWorkflowsForUser,
  dispatchDueCronWorkflows,
  getWorkflowsQueue,
  startWorkflowsWorker,
  stopWorkflowsWorker,
  closeWorkflowsQueue,
  scheduleRepeatableWorkflowsJobs,
  type ActivateWorkflowArgs,
  type CreateWorkflowDraftArgs,
  type InactiveWorkflowStatus,
  type ReviseWorkflowArgs,
  type WorkflowDefinitionDraft,
  type WorkflowDefinitionPatch,
  type WorkflowRevisedOutcome,
  type WorkflowRevisionOutcome,
  type WorkflowRevisionProblem,
  type WorkflowRevisionProblemCode,
  type WorkflowServiceFailure,
  type WorkflowServiceResult,
  type WorkflowApprovalEditPreparation,
  type TickResult,
  type WorkflowsJobData,
  type StartWorkflowsWorkerOpts,
} from "@alfred/assistant/automation";

// HTTP transport
export { workflowRoutes } from "./routes";
