/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowsWorkflowRouteImport } from './routes/workflows.$workflow'
import { Route as SkillsSlugRouteImport } from './routes/skills.$slug'
import { Route as PreviewWorkflowsRouteImport } from './routes/preview.workflows'
import { Route as PreviewVisitorsNowRouteImport } from './routes/preview.visitors-now'
import { Route as PreviewSettingsRouteImport } from './routes/preview.settings'
import { Route as PreviewOnboardingRouteImport } from './routes/preview.onboarding'
import { Route as PreviewLandingRouteImport } from './routes/preview.landing'
import { Route as PreviewIntegrationsRouteImport } from './routes/preview.integrations'
import { Route as PreviewChatRouteImport } from './routes/preview.chat'
import { Route as LibraryArtifactRouteImport } from './routes/library.$artifact'
import { Route as IntegrationsProviderRouteImport } from './routes/integrations.$provider'
import { Route as DebugEventsRouteImport } from './routes/debug.events'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsWorkflowRoute = WorkflowsWorkflowRouteImport.update({
  id: '/$workflow',
  path: '/$workflow',
  getParentRoute: () => WorkflowsRoute,
} as any)
const SkillsSlugRoute = SkillsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SkillsRoute,
} as any)
const PreviewWorkflowsRoute = PreviewWorkflowsRouteImport.update({
  id: '/preview/workflows',
  path: '/preview/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewVisitorsNowRoute = PreviewVisitorsNowRouteImport.update({
  id: '/preview/visitors-now',
  path: '/preview/visitors-now',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewSettingsRoute = PreviewSettingsRouteImport.update({
  id: '/preview/settings',
  path: '/preview/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewOnboardingRoute = PreviewOnboardingRouteImport.update({
  id: '/preview/onboarding',
  path: '/preview/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewLandingRoute = PreviewLandingRouteImport.update({
  id: '/preview/landing',
  path: '/preview/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewIntegrationsRoute = PreviewIntegrationsRouteImport.update({
  id: '/preview/integrations',
  path: '/preview/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewChatRoute = PreviewChatRouteImport.update({
  id: '/preview/chat',
  path: '/preview/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryArtifactRoute = LibraryArtifactRouteImport.update({
  id: '/$artifact',
  path: '/$artifact',
  getParentRoute: () => LibraryRoute,
} as any)
const IntegrationsProviderRoute = IntegrationsProviderRouteImport.update({
  id: '/$provider',
  path: '/$provider',
  getParentRoute: () => IntegrationsRoute,
} as any)
const DebugEventsRoute = DebugEventsRouteImport.update({
  id: '/debug/events',
  path: '/debug/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/library': typeof LibraryRouteWithChildren
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRouteWithChildren
  '/styleguide': typeof StyleguideRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/debug/events': typeof DebugEventsRoute
  '/integrations/$provider': typeof IntegrationsProviderRoute
  '/library/$artifact': typeof LibraryArtifactRoute
  '/preview/chat': typeof PreviewChatRoute
  '/preview/integrations': typeof PreviewIntegrationsRoute
  '/preview/landing': typeof PreviewLandingRoute
  '/preview/onboarding': typeof PreviewOnboardingRoute
  '/preview/settings': typeof PreviewSettingsRoute
  '/preview/visitors-now': typeof PreviewVisitorsNowRoute
  '/preview/workflows': typeof PreviewWorkflowsRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/workflows/$workflow': typeof WorkflowsWorkflowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/library': typeof LibraryRouteWithChildren
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRouteWithChildren
  '/styleguide': typeof StyleguideRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/debug/events': typeof DebugEventsRoute
  '/integrations/$provider': typeof IntegrationsProviderRoute
  '/library/$artifact': typeof LibraryArtifactRoute
  '/preview/chat': typeof PreviewChatRoute
  '/preview/integrations': typeof PreviewIntegrationsRoute
  '/preview/landing': typeof PreviewLandingRoute
  '/preview/onboarding': typeof PreviewOnboardingRoute
  '/preview/settings': typeof PreviewSettingsRoute
  '/preview/visitors-now': typeof PreviewVisitorsNowRoute
  '/preview/workflows': typeof PreviewWorkflowsRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/workflows/$workflow': typeof WorkflowsWorkflowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/library': typeof LibraryRouteWithChildren
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/notes': typeof NotesRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRouteWithChildren
  '/styleguide': typeof StyleguideRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/debug/events': typeof DebugEventsRoute
  '/integrations/$provider': typeof IntegrationsProviderRoute
  '/library/$artifact': typeof LibraryArtifactRoute
  '/preview/chat': typeof PreviewChatRoute
  '/preview/integrations': typeof PreviewIntegrationsRoute
  '/preview/landing': typeof PreviewLandingRoute
  '/preview/onboarding': typeof PreviewOnboardingRoute
  '/preview/settings': typeof PreviewSettingsRoute
  '/preview/visitors-now': typeof PreviewVisitorsNowRoute
  '/preview/workflows': typeof PreviewWorkflowsRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/workflows/$workflow': typeof WorkflowsWorkflowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/integrations'
    | '/library'
    | '/login'
    | '/memory'
    | '/notes'
    | '/onboarding'
    | '/settings'
    | '/skills'
    | '/styleguide'
    | '/workflows'
    | '/chat/$threadId'
    | '/debug/events'
    | '/integrations/$provider'
    | '/library/$artifact'
    | '/preview/chat'
    | '/preview/integrations'
    | '/preview/landing'
    | '/preview/onboarding'
    | '/preview/settings'
    | '/preview/visitors-now'
    | '/preview/workflows'
    | '/skills/$slug'
    | '/workflows/$workflow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/integrations'
    | '/library'
    | '/login'
    | '/memory'
    | '/notes'
    | '/onboarding'
    | '/settings'
    | '/skills'
    | '/styleguide'
    | '/workflows'
    | '/chat/$threadId'
    | '/debug/events'
    | '/integrations/$provider'
    | '/library/$artifact'
    | '/preview/chat'
    | '/preview/integrations'
    | '/preview/landing'
    | '/preview/onboarding'
    | '/preview/settings'
    | '/preview/visitors-now'
    | '/preview/workflows'
    | '/skills/$slug'
    | '/workflows/$workflow'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/integrations'
    | '/library'
    | '/login'
    | '/memory'
    | '/notes'
    | '/onboarding'
    | '/settings'
    | '/skills'
    | '/styleguide'
    | '/workflows'
    | '/chat/$threadId'
    | '/debug/events'
    | '/integrations/$provider'
    | '/library/$artifact'
    | '/preview/chat'
    | '/preview/integrations'
    | '/preview/landing'
    | '/preview/onboarding'
    | '/preview/settings'
    | '/preview/visitors-now'
    | '/preview/workflows'
    | '/skills/$slug'
    | '/workflows/$workflow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  IntegrationsRoute: typeof IntegrationsRouteWithChildren
  LibraryRoute: typeof LibraryRouteWithChildren
  LoginRoute: typeof LoginRoute
  MemoryRoute: typeof MemoryRoute
  NotesRoute: typeof NotesRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRouteWithChildren
  StyleguideRoute: typeof StyleguideRoute
  WorkflowsRoute: typeof WorkflowsRouteWithChildren
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  DebugEventsRoute: typeof DebugEventsRoute
  PreviewChatRoute: typeof PreviewChatRoute
  PreviewIntegrationsRoute: typeof PreviewIntegrationsRoute
  PreviewLandingRoute: typeof PreviewLandingRoute
  PreviewOnboardingRoute: typeof PreviewOnboardingRoute
  PreviewSettingsRoute: typeof PreviewSettingsRoute
  PreviewVisitorsNowRoute: typeof PreviewVisitorsNowRoute
  PreviewWorkflowsRoute: typeof PreviewWorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflow': {
      id: '/workflows/$workflow'
      path: '/$workflow'
      fullPath: '/workflows/$workflow'
      preLoaderRoute: typeof WorkflowsWorkflowRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/skills/$slug': {
      id: '/skills/$slug'
      path: '/$slug'
      fullPath: '/skills/$slug'
      preLoaderRoute: typeof SkillsSlugRouteImport
      parentRoute: typeof SkillsRoute
    }
    '/preview/workflows': {
      id: '/preview/workflows'
      path: '/preview/workflows'
      fullPath: '/preview/workflows'
      preLoaderRoute: typeof PreviewWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/visitors-now': {
      id: '/preview/visitors-now'
      path: '/preview/visitors-now'
      fullPath: '/preview/visitors-now'
      preLoaderRoute: typeof PreviewVisitorsNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/settings': {
      id: '/preview/settings'
      path: '/preview/settings'
      fullPath: '/preview/settings'
      preLoaderRoute: typeof PreviewSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/onboarding': {
      id: '/preview/onboarding'
      path: '/preview/onboarding'
      fullPath: '/preview/onboarding'
      preLoaderRoute: typeof PreviewOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/landing': {
      id: '/preview/landing'
      path: '/preview/landing'
      fullPath: '/preview/landing'
      preLoaderRoute: typeof PreviewLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/integrations': {
      id: '/preview/integrations'
      path: '/preview/integrations'
      fullPath: '/preview/integrations'
      preLoaderRoute: typeof PreviewIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/chat': {
      id: '/preview/chat'
      path: '/preview/chat'
      fullPath: '/preview/chat'
      preLoaderRoute: typeof PreviewChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$artifact': {
      id: '/library/$artifact'
      path: '/$artifact'
      fullPath: '/library/$artifact'
      preLoaderRoute: typeof LibraryArtifactRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/integrations/$provider': {
      id: '/integrations/$provider'
      path: '/$provider'
      fullPath: '/integrations/$provider'
      preLoaderRoute: typeof IntegrationsProviderRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/debug/events': {
      id: '/debug/events'
      path: '/debug/events'
      fullPath: '/debug/events'
      preLoaderRoute: typeof DebugEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface IntegrationsRouteChildren {
  IntegrationsProviderRoute: typeof IntegrationsProviderRoute
}

const IntegrationsRouteChildren: IntegrationsRouteChildren = {
  IntegrationsProviderRoute: IntegrationsProviderRoute,
}

const IntegrationsRouteWithChildren = IntegrationsRoute._addFileChildren(
  IntegrationsRouteChildren,
)

interface LibraryRouteChildren {
  LibraryArtifactRoute: typeof LibraryArtifactRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryArtifactRoute: LibraryArtifactRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

interface SkillsRouteChildren {
  SkillsSlugRoute: typeof SkillsSlugRoute
}

const SkillsRouteChildren: SkillsRouteChildren = {
  SkillsSlugRoute: SkillsSlugRoute,
}

const SkillsRouteWithChildren =
  SkillsRoute._addFileChildren(SkillsRouteChildren)

interface WorkflowsRouteChildren {
  WorkflowsWorkflowRoute: typeof WorkflowsWorkflowRoute
}

const WorkflowsRouteChildren: WorkflowsRouteChildren = {
  WorkflowsWorkflowRoute: WorkflowsWorkflowRoute,
}

const WorkflowsRouteWithChildren = WorkflowsRoute._addFileChildren(
  WorkflowsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  IntegrationsRoute: IntegrationsRouteWithChildren,
  LibraryRoute: LibraryRouteWithChildren,
  LoginRoute: LoginRoute,
  MemoryRoute: MemoryRoute,
  NotesRoute: NotesRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRouteWithChildren,
  StyleguideRoute: StyleguideRoute,
  WorkflowsRoute: WorkflowsRouteWithChildren,
  ChatThreadIdRoute: ChatThreadIdRoute,
  DebugEventsRoute: DebugEventsRoute,
  PreviewChatRoute: PreviewChatRoute,
  PreviewIntegrationsRoute: PreviewIntegrationsRoute,
  PreviewLandingRoute: PreviewLandingRoute,
  PreviewOnboardingRoute: PreviewOnboardingRoute,
  PreviewSettingsRoute: PreviewSettingsRoute,
  PreviewVisitorsNowRoute: PreviewVisitorsNowRoute,
  PreviewWorkflowsRoute: PreviewWorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
