/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsSlugRouteImport } from './routes/skills.$slug'
import { Route as IntegrationsProviderRouteImport } from './routes/integrations.$provider'
import { Route as DebugEventsRouteImport } from './routes/debug.events'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSlugRoute = SkillsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SkillsRoute,
} as any)
const IntegrationsProviderRoute = IntegrationsProviderRouteImport.update({
  id: '/$provider',
  path: '/$provider',
  getParentRoute: () => IntegrationsRoute,
} as any)
const DebugEventsRoute = DebugEventsRouteImport.update({
  id: '/debug/events',
  path: '/debug/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRouteWithChildren
  '/styleguide': typeof StyleguideRoute
  '/workflows': typeof WorkflowsRoute
  '/debug/events': typeof DebugEventsRoute
  '/integrations/$provider': typeof IntegrationsProviderRoute
  '/skills/$slug': typeof SkillsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRouteWithChildren
  '/styleguide': typeof StyleguideRoute
  '/workflows': typeof WorkflowsRoute
  '/debug/events': typeof DebugEventsRoute
  '/integrations/$provider': typeof IntegrationsProviderRoute
  '/skills/$slug': typeof SkillsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRouteWithChildren
  '/styleguide': typeof StyleguideRoute
  '/workflows': typeof WorkflowsRoute
  '/debug/events': typeof DebugEventsRoute
  '/integrations/$provider': typeof IntegrationsProviderRoute
  '/skills/$slug': typeof SkillsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/integrations'
    | '/library'
    | '/login'
    | '/memory'
    | '/notes'
    | '/settings'
    | '/skills'
    | '/styleguide'
    | '/workflows'
    | '/debug/events'
    | '/integrations/$provider'
    | '/skills/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/integrations'
    | '/library'
    | '/login'
    | '/memory'
    | '/notes'
    | '/settings'
    | '/skills'
    | '/styleguide'
    | '/workflows'
    | '/debug/events'
    | '/integrations/$provider'
    | '/skills/$slug'
  id:
    | '__root__'
    | '/'
    | '/integrations'
    | '/library'
    | '/login'
    | '/memory'
    | '/notes'
    | '/settings'
    | '/skills'
    | '/styleguide'
    | '/workflows'
    | '/debug/events'
    | '/integrations/$provider'
    | '/skills/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntegrationsRoute: typeof IntegrationsRouteWithChildren
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  MemoryRoute: typeof MemoryRoute
  NotesRoute: typeof NotesRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRouteWithChildren
  StyleguideRoute: typeof StyleguideRoute
  WorkflowsRoute: typeof WorkflowsRoute
  DebugEventsRoute: typeof DebugEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$slug': {
      id: '/skills/$slug'
      path: '/$slug'
      fullPath: '/skills/$slug'
      preLoaderRoute: typeof SkillsSlugRouteImport
      parentRoute: typeof SkillsRoute
    }
    '/integrations/$provider': {
      id: '/integrations/$provider'
      path: '/$provider'
      fullPath: '/integrations/$provider'
      preLoaderRoute: typeof IntegrationsProviderRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/debug/events': {
      id: '/debug/events'
      path: '/debug/events'
      fullPath: '/debug/events'
      preLoaderRoute: typeof DebugEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface IntegrationsRouteChildren {
  IntegrationsProviderRoute: typeof IntegrationsProviderRoute
}

const IntegrationsRouteChildren: IntegrationsRouteChildren = {
  IntegrationsProviderRoute: IntegrationsProviderRoute,
}

const IntegrationsRouteWithChildren = IntegrationsRoute._addFileChildren(
  IntegrationsRouteChildren,
)

interface SkillsRouteChildren {
  SkillsSlugRoute: typeof SkillsSlugRoute
}

const SkillsRouteChildren: SkillsRouteChildren = {
  SkillsSlugRoute: SkillsSlugRoute,
}

const SkillsRouteWithChildren =
  SkillsRoute._addFileChildren(SkillsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntegrationsRoute: IntegrationsRouteWithChildren,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  MemoryRoute: MemoryRoute,
  NotesRoute: NotesRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRouteWithChildren,
  StyleguideRoute: StyleguideRoute,
  WorkflowsRoute: WorkflowsRoute,
  DebugEventsRoute: DebugEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
