export const COMPACTION_THRESHOLD_PCT = 0.6;

export function compactionThresholdTokens(modelContextWindow: number): number {
  return Math.floor(modelContextWindow * COMPACTION_THRESHOLD_PCT);
}

export const SCRATCH_TTL_SECONDS = 30 * 24 * 60 * 60;

/**
 * Scratchpad key constraints (caller-enforced):
 * `runId`, `subId`, and `path` MUST NOT contain `:` or `.` — both are
 * structural delimiters in the key shape. `runId` is generated by
 * `createId('run')` (alphanumeric + `_`) so it's safe by construction;
 * `subId` and `path` are runtime-controlled and rely on this contract.
 * Violations could let a malicious or buggy input forge keys outside its
 * zone, bypassing dispatcher zone enforcement (Phase 6).
 */
export function sharedKey(
  runId: string,
  path: string,
): `alfred:scratch:${string}:shared.${string}` {
  return `alfred:scratch:${runId}:shared.${path}`;
}

export function subAgentKey(
  runId: string,
  subId: string,
  path: string,
): `alfred:scratch:${string}:scratch.${string}.${string}` {
  return `alfred:scratch:${runId}:scratch.${subId}.${path}`;
}

export interface ScratchEntry<T = unknown> {
  value: T;
  zone: "shared" | "scratch";
  writtenBy: string;
  writtenAt: number;
}
