export const COMPACTION_THRESHOLD_PCT = 0.6;

export function compactionThresholdTokens(modelContextWindow: number): number {
  return Math.floor(modelContextWindow * COMPACTION_THRESHOLD_PCT);
}

export const SCRATCH_TTL_SECONDS = 30 * 24 * 60 * 60;

/**
 * How long a gated `action_stagings` row waits for a human decision
 * before the `staging-expire` worker auto-rejects it (status='expired',
 * reason='auto-expired'; the boss receives the structured auto-expired
 * rejection on resume). Fixed window for v1 — ADR-0034's "per-tool
 * default at staging time" is deferred until a product need for
 * per-tool/per-policy windows appears (Phase 5e note in m13-plan).
 */
export const APPROVAL_EXPIRY_MS = 24 * 60 * 60 * 1000;

// Scratchpad key parts must not contain `:` or `.` — both are structural
// delimiters in the key shape. `runId` (generated by `createId('run')`)
// is safe by construction; `subId` and `path` are runtime-controlled and
// must satisfy this contract or they could forge keys outside their
// zone and bypass dispatcher zone enforcement (Phase 6). Enforced at
// runtime by `assertScratchKeyPart` below.
function assertScratchKeyPart(name: string, value: string): void {
  if (value.length === 0 || value.includes(":") || value.includes(".")) {
    throw new Error(
      `[scratchpad] ${name} must be non-empty and contain no ':' or '.' (got: ${JSON.stringify(value)})`,
    );
  }
}

/**
 * The run-scoped prefix shared by every scratch key (`alfred:scratch:<runId>:`).
 * Single source for the key grammar's prefix so the builders below and any code
 * that strips it back to the logical (dotted) form derive the same offset and
 * can never drift apart.
 */
export function scratchKeyPrefix(runId: string): `alfred:scratch:${string}:` {
  return `alfred:scratch:${runId}:`;
}

export function sharedKey(
  runId: string,
  path: string,
): `alfred:scratch:${string}:shared.${string}` {
  assertScratchKeyPart("runId", runId);
  assertScratchKeyPart("path", path);
  return `${scratchKeyPrefix(runId)}shared.${path}`;
}

export function subAgentKey(
  runId: string,
  subId: string,
  path: string,
): `alfred:scratch:${string}:scratch.${string}.${string}` {
  assertScratchKeyPart("runId", runId);
  assertScratchKeyPart("subId", subId);
  assertScratchKeyPart("path", path);
  return `${scratchKeyPrefix(runId)}scratch.${subId}.${path}`;
}

/**
 * Strip the run prefix from a full scratch key, yielding its logical (dotted)
 * form (`shared.<path>` / `scratch.<subId>.<path>`) — the form persisted as the
 * Postgres snapshot `key` and the only key identity health spans hash. The
 * slice offset comes from `scratchKeyPrefix`, so it cannot drift from the
 * builders' prefix.
 */
export function logicalScratchKey(runId: string, fullKey: string): string {
  return fullKey.slice(scratchKeyPrefix(runId).length);
}

/** The two scratchpad zones: boss-owned `shared.*` and per-sub-agent `scratch.*`. */
export const SCRATCH_ZONES = ["shared", "scratch"] as const;
export type ScratchZone = (typeof SCRATCH_ZONES)[number];

export interface ScratchEntry<T = unknown> {
  value: T;
  zone: ScratchZone;
  writtenBy: string;
  writtenAt: number;
}
