export const COMPACTION_THRESHOLD_PCT = 0.6;

export function compactionThresholdTokens(modelContextWindow: number): number {
  return Math.floor(modelContextWindow * COMPACTION_THRESHOLD_PCT);
}

export const SCRATCH_TTL_SECONDS = 30 * 24 * 60 * 60;

// Scratchpad key parts must not contain `:` or `.` — both are structural
// delimiters in the key shape. `runId` (generated by `createId('run')`)
// is safe by construction; `subId` and `path` are runtime-controlled and
// must satisfy this contract or they could forge keys outside their
// zone and bypass dispatcher zone enforcement (Phase 6). Enforced at
// runtime by `assertScratchKeyPart` below.
function assertScratchKeyPart(name: string, value: string): void {
  if (value.length === 0 || value.includes(":") || value.includes(".")) {
    throw new Error(
      `[scratchpad] ${name} must be non-empty and contain no ':' or '.' (got: ${JSON.stringify(value)})`,
    );
  }
}

export function sharedKey(
  runId: string,
  path: string,
): `alfred:scratch:${string}:shared.${string}` {
  assertScratchKeyPart("runId", runId);
  assertScratchKeyPart("path", path);
  return `alfred:scratch:${runId}:shared.${path}`;
}

export function subAgentKey(
  runId: string,
  subId: string,
  path: string,
): `alfred:scratch:${string}:scratch.${string}.${string}` {
  assertScratchKeyPart("runId", runId);
  assertScratchKeyPart("subId", subId);
  assertScratchKeyPart("path", path);
  return `alfred:scratch:${runId}:scratch.${subId}.${path}`;
}

export interface ScratchEntry<T = unknown> {
  value: T;
  zone: "shared" | "scratch";
  writtenBy: string;
  writtenAt: number;
}
