import { Markdown } from "@react-email/components";
import { render } from "@react-email/render";
import * as React from "react";
import { bodyStyles, EmailShell } from "./_shell";

/**
 * The "skill documented" email — a delivery receipt sent when a skill-doc
 * run completes. Renders the shared shell (logo + card + footer) with a
 * greeting, the provenance line (sources scanned), a "What's covered"
 * preview of the documented body, and a "Review or edit" footer CTA.
 *
 * The body is *not* generated by an LLM — the documented skill body is the
 * model artifact and lives in the app; this email just previews the first
 * ~600 chars the caller already trimmed.
 */

export interface SkillDocumentationEmailProps {
  /** First name for the greeting; falls back to "there". */
  greetingName?: string;
  /** Provenance preamble, e.g. "Analyzed 12 document chunks across Gmail …". */
  provenance?: string;
  /** Trimmed markdown preview of the documented body. */
  preview?: string;
  /** Deep link the footer CTA points at. Omitted → no CTA. */
  skillUrl?: string;
  logoUrl?: string;
  createdAt?: string;
  timezone?: string;
}

const DEFAULT_PREVIEW = `## When to reach for this

Use this skill when a teammate asks for a status rollup across the active
warden PRs. Pull the open PRs, group by milestone, and summarize what each
unblocks.`;

export const SkillDocumentationEmail = ({
  greetingName = "there",
  provenance = "Analyzed 12 document chunks across Gmail and 3 memory notes to enrich this skill.",
  preview = DEFAULT_PREVIEW,
  skillUrl = "http://localhost:3000/skills/status-rollup",
  logoUrl,
  createdAt = new Date().toISOString(),
  timezone,
}: SkillDocumentationEmailProps): React.ReactElement => {
  return (
    <EmailShell
      previewText={provenance}
      logoUrl={logoUrl}
      createdAt={createdAt}
      timezone={timezone}
      ctaUrl={skillUrl}
      ctaLabel="Review or edit"
    >
      <p style={bodyStyles.paragraph}>Hi {greetingName},</p>
      <p style={bodyStyles.paragraph}>{provenance}</p>
      <p style={{ ...bodyStyles.paragraph, margin: "0 0 8px 0" }}>
        <strong style={bodyStyles.strong}>What&apos;s covered:</strong>
      </p>
      {/* The preview is the documented skill body — markdown the user already
          approved — so render it, don't show it verbatim. */}
      <div
        style={{
          background: "#f8fafc",
          padding: "4px 20px",
          borderRadius: "8px",
          border: "1px solid #e5e7eb",
        }}
      >
        <Markdown
          markdownCustomStyles={{
            h1: { ...bodyStyles.heading, fontSize: "16px", margin: "16px 0 8px 0" },
            h2: { ...bodyStyles.heading, fontSize: "15px", margin: "16px 0 8px 0" },
            h3: { ...bodyStyles.heading, fontSize: "14px", margin: "16px 0 8px 0" },
            p: { ...bodyStyles.paragraph, fontSize: "14px", margin: "0 0 12px 0" },
            bold: bodyStyles.strong,
            ul: {
              ...bodyStyles.paragraph,
              fontSize: "14px",
              margin: "0 0 12px 0",
              paddingLeft: "20px",
            },
            ol: {
              ...bodyStyles.paragraph,
              fontSize: "14px",
              margin: "0 0 12px 0",
              paddingLeft: "20px",
            },
            li: { color: "#374151", margin: "0 0 6px 0" },
            link: bodyStyles.link,
            codeInline: {
              background: "#eef2f7",
              borderRadius: "4px",
              padding: "1px 5px",
              fontSize: "13px",
            },
          }}
        >
          {preview}
        </Markdown>
      </div>
    </EmailShell>
  );
};

SkillDocumentationEmail.PreviewProps = {
  greetingName: "Yash",
  logoUrl: "http://localhost:3000/images/logo/alfred-logo-email.png",
} satisfies SkillDocumentationEmailProps;

export default SkillDocumentationEmail;

/** Render the skill-documentation email to an HTML string for sending. */
export const renderSkillDocumentationEmail = (
  props: SkillDocumentationEmailProps,
): Promise<string> => render(<SkillDocumentationEmail {...props} />);
