// Transitional barrel: re-exports skills domain logic from @alfred/assistant/skills
// and routes from ./routes for backward compatibility during the 6B migration.
// This keeps @alfred/api/backend surface byte-identical while moving the domain module.
// Skills module includes flattened skill-revisions and skill-documentation.
export {
  LEARN_SKILL_WORKFLOW_SLUG,
  learnSkillDedupKey,
  learnSkillWorkflowInputSchema,
  MENTION_KINDS,
  parseMentions,
  parsedMentionSchema,
  resolveMentions,
  collectSkillLearnContext,
  distillResultSchema,
  distillSkill,
  skillProposalSchema,
  learnSkillWorkflow,
  slugifyForUser,
  commitSkillRevision,
  finalizeSkillRun,
  recordSkillRun,
  SKILL_DOCUMENTATION_WORKFLOW_SLUG,
  skillDocumentationDedupKey,
  skillDocumentationInputSchema,
  collectSkillDocumentationContext,
  composeSkillDocumentation,
  composeSkillDocumentationEmail,
  skillDocumentationWorkflow,
  type LearnSkillWorkflowInput,
  type MentionKind,
  type MentionRegistry,
  type ParsedMention,
  type SkillLearnContext,
  type DistillResult,
  type DistillSkillArgs,
  type DistillSkillResult,
  type SkillProposal,
  type CommitRevisionArgs,
  type CommitRevisionResult,
  type FinalizeSkillRunArgs,
  type RecordSkillRunArgs,
  type SkillDocumentationInput,
  type SkillDocumentationContext,
  type ComposeArgs,
  type ComposedDocumentation,
  type SkillDocumentationEmailArgs,
} from "@alfred/assistant/skills";

// HTTP transport
export { skillsRoutes } from "./routes";
