import { sql } from "drizzle-orm";
import {
  boolean,
  index,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { createId, lifecycle_dates } from "../helpers";
import { user } from "./auth";

/**
 * Skills (ADR-0017).
 *
 * A skill is a markdown body + structured metadata the agent can mount
 * into its system prompt. Authoring follows dimension's two-phase Learn:
 *
 *   1. sync `learn-skill` workflow distills the user's prompt + existing
 *      memory into a v1 body and proposes user_facts;
 *   2. async `skill-documentation` workflow runs deep hybrid search across
 *      connected integrations and writes a v2 body with named entities.
 *
 * Both phases append a `skill_revisions` row; `skills.current_revision_id`
 * always points at the latest successful one. The HIL gate (approve /
 * regenerate / reject) lives on the *fact proposals* via the existing
 * ADR-0019 flow — the body itself isn't gated, just cancellable on
 * explicit reject.
 *
 * Built-in skills (alfred-curated) live as files in
 * `apps/server/src/builtins/skills/<slug>.md` and seed into this table at
 * deploy time with `is_builtin=true`. They skip the Learn pipeline.
 */
export const skills = pgTable(
  "skills",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => createId("skl")),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    /** URL-safe identifier, unique per user. Stable across revisions. */
    slug: text("slug").notNull(),
    /** Display name, auto-generated by the Learn step on first save. */
    name: text("name").notNull(),
    description: text("description"),
    /**
     * Pointer to the active revision. Null until the first successful
     * Learn run commits a body. Read-side: render skills with non-null
     * `current_revision_id`; the others are still being learned.
     */
    currentRevisionId: text("current_revision_id"),
    /** active | draft | archived. Authoring stays in draft until first revision lands. */
    status: text("status").notNull().default("draft"),
    /** True for alfred-curated skills shipped from the repo; false for user-authored. */
    isBuiltin: boolean("is_builtin").notNull().default(false),
    /**
     * Last execution of the skill (not the last *learn* — that's on
     * `skill_runs`). Refreshed when an agent run mounts this skill via
     * `@skill:<slug>`.
     */
    lastInvokedAt: timestamp("last_invoked_at", { withTimezone: true }),
    ...lifecycle_dates,
  },
  (t) => [
    uniqueIndex("skills_slug_idx").on(t.userId, t.slug),
    index("skills_user_status_idx").on(t.userId, t.status, t.updatedAt),
  ],
);

/**
 * Versioned body of a skill. One row per Learn-phase output:
 *  - `kind='distilled'` — sync output of the `learn-skill` workflow;
 *  - `kind='documented'` — async output of `skill-documentation`;
 *  - `kind='manual'`    — direct user edit via the markdown editor.
 *
 * Append-only. `skills.current_revision_id` advances to the newest row;
 * older rows remain for the History tab and for diffing.
 */
export const skillRevisions = pgTable(
  "skill_revisions",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => createId("skr")),
    skillId: text("skill_id")
      .notNull()
      .references(() => skills.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    /** distilled | documented | manual — see file header. */
    kind: text("kind").notNull(),
    /** Canonical skill body (markdown). The agent mounts this into its system prompt. */
    body: text("body").notNull(),
    /**
     * Parsed structured metadata derived from `body`. Shape:
     *   {
     *     mentions: { kind: 'integration'|'skill'|'collaborator', slug: string }[],
     *     tools?: string[],            // optional explicit allowlist (frontmatter)
     *     defaultModel?: string,
     *     activationKeywords?: string[],
     *     examples?: { input: string; output: string }[]
     *   }
     */
    metadata: jsonb("metadata").notNull().default(sql`'{}'::jsonb`),
    /** Pointer to the `agent_runs.id` that produced this revision (null for `manual`). */
    createdByRunId: text("created_by_run_id"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    index("skill_revisions_skill_idx").on(t.skillId, t.createdAt),
    index("skill_revisions_user_idx").on(t.userId, t.createdAt),
  ],
);

/**
 * One row per Learn click — populates the History tab.
 *
 * A run links a skill to the agent run executing one of the two Learn
 * workflows (`learn-skill` or `skill-documentation`). Status mirrors the
 * agent run for cheap UI reads without a join. The `producedRevisionId`
 * column is set when the run successfully writes a `skill_revisions`
 * row; null while running, on cancel, or on error.
 */
export const skillRuns = pgTable(
  "skill_runs",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => createId("sklrn")),
    skillId: text("skill_id")
      .notNull()
      .references(() => skills.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    /** learn | document — which Learn-phase workflow this row tracks. */
    kind: text("kind").notNull(),
    /** Pointer to `agent_runs.id`. Source of truth for cost, status detail, error. */
    agentRunId: text("agent_run_id").notNull(),
    /**
     * Mirrors `agent_runs.status`: pending|runnable|running|waiting|completed|failed|cancelled.
     * Updated on terminal transitions; intermediate states observed via the SSE bus.
     */
    status: text("status").notNull().default("pending"),
    /** Set on success. Null while the run is in flight or after a failure. */
    producedRevisionId: text("produced_revision_id"),
    startedAt: timestamp("started_at", { withTimezone: true }).defaultNow().notNull(),
    endedAt: timestamp("ended_at", { withTimezone: true }),
  },
  (t) => [
    index("skill_runs_skill_idx").on(t.skillId, t.startedAt),
    index("skill_runs_user_kind_idx").on(t.userId, t.kind, t.startedAt),
    uniqueIndex("skill_runs_agent_run_idx").on(t.agentRunId),
  ],
);
